const ADD_TODO = 'ADD_TODO';
const TOGGLE_TODO = 'TOGGLE_TODO';
const COMPLETE_TODO = 'COMPLETE_TODO';
const DELTE_TODO = 'DLETE_TODO';
const SET_TODOLIST_FILTER = 'SET_TODOLIST_FILTER';
const SHOW_ALL = 'SHOW_ALL';
const SHOW_ACTIVE = 'SHOW_ACTIVE';
const SHOW_COMPLETED = 'SHOW_COMPLETED';

export {
  ADD_TODO,
  TOGGLE_TODO,
  COMPLETE_TODO,
  DELTE_TODO,
  SET_TODOLIST_FILTER,
  SHOW_ALL,
  SHOW_ACTIVE,
  SHOW_COMPLETED,
};
